//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bids
    {
        public int Bid_ID { get; set; }
        public int Client_ID { get; set; }
        public int Staff_ID { get; set; }
        public int Purchase_ID { get; set; }
        public int Status_ID { get; set; }
        public string Address { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Purchases Purchases { get; set; }
        public virtual Staffs Staffs { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
